### ISSUE TITLE
Inventory bug

### ISSUE THREAD

**Issue by Chargedx** [Globox1997/BackSlotAddon#1]
The inventory slots are bugged in the inventory. How do I fix that?
![Screenshot 2021-07-27 113930](https://user-images.githubusercontent.com/88047434/127184477-e18b2363-fdc2-4850-9559-6a7b73526388.png)

**Comment by Globox1997** [comment]
This is an issue for the main mod [https://github.com/Globox1997/BackSlot/issues/23](https://github.com/Globox1997/BackSlot/issues/23)
