### ISSUE TITLE
Bizarre Shields

### ISSUE THREAD

**Issue by CountSjorn52** [Globox1997/BackSlotAddon#12]
Been using the recent version of backslot both the main mod and addon 1.18.2 and all three of the shields from MCDW are absurdly large one of which is facing the wrong direction. Chronos and i tried various things to fix it but nothing worked i think it's this mods problem not his.

![2022-08-29_08 53 06](https://user-images.githubusercontent.com/93433681/187312649-17a6ebac-5a1d-477a-b182-d3f0dd08a224.png)
![2022-08-29_08 53 14](https://user-images.githubusercontent.com/93433681/187312651-1eb2950c-8124-41c5-8802-1c2cb0b9f9c5.png)
![2022-08-29_09 16 28](https://user-images.githubusercontent.com/93433681/187312653-63a3b6d0-cc59-4cd0-8d24-2a3052bcfb3d.png)

**Comment by Globox1997** [comment]
You can fix that by editing the head models of those items with a resource pack :) for further information check out my discord
