### ISSUE TITLE
Use a mixin config plugin to disable or enable mixins if the mod isnt present

### ISSUE THREAD

**Issue by Linguardium** [Globox1997/BackSlotAddon#20]
https://github.com/Globox1997/BackSlotAddon/blob/1292830eaefc25178046f8a68d894743ae1d667b/src/main/java/net/backslotaddon/mixin/compat/IdMapUniformsMixin.java#L29

you are throwing errors because you arent controlling whether to load your mixins or not. fix that with a mixin config plugin

**Comment by Globox1997** [comment]
Should be already the case with [https://github.com/Globox1997/BackSlotAddon/blob/1292830eaefc25178046f8a68d894743ae1d667b/src/main/java/net/backslotaddon/mixin/BackSlotAddonMixinPlugin.java#L25](https://github.com/Globox1997/BackSlotAddon/blob/1292830eaefc25178046f8a68d894743ae1d667b/src/main/java/net/backslotaddon/mixin/BackSlotAddonMixinPlugin.java#L25)

**Comment by Linguardium** [comment]
I would have to check the error logs I had collected. Is your mixin version locked to the version of the mod you are modifying? 

Not sure what your local setup is but your iris version looks old in your build.gradle for the 1.21 branch too

**Comment by Globox1997** [comment]
Seems like I kinda forgot about it. Updated it with [https://github.com/Globox1997/BackSlotAddon/commit/b561a95f1d1ca6f2babe17f6df13f7c4c6699ab4](https://github.com/Globox1997/BackSlotAddon/commit/b561a95f1d1ca6f2babe17f6df13f7c4c6699ab4)
