### ISSUE TITLE
shield model clipping

### ISSUE THREAD

**Issue by Heamaci** [Globox1997/BackSlotAddon#3]
![imagen](https://user-images.githubusercontent.com/67716228/136631953-1244f95b-206f-4635-a434-3089115569d5.png)

putting a shield in your back slot has the handle part clipping through your body.

**Comment by Globox1997** [comment]
Basically the reason why this feature isn't in the main mod.
If I change the position the shield will be further away from the body which looks odd in my opinion, what do you think?
![2021-10-13_11 59 50](https://user-images.githubusercontent.com/55102939/137112103-26911d2c-1aa0-47a0-857c-79bb814dac9d.png)

**Comment by Globox1997** [comment]
Added a config which is off by default in the latest version with [https://github.com/Globox1997/BackSlotAddon/commit/554a46c73cdc4d09bc4bdc594a2a0eb7c7e46dd0](https://github.com/Globox1997/BackSlotAddon/commit/554a46c73cdc4d09bc4bdc594a2a0eb7c7e46dd0)
