### ISSUE TITLE
Shield to automatically equip in offhand slot

### ISSUE THREAD

**Issue by CapoFantasma97** [Globox1997/BackSlotAddon#4]
Shield should automatically equip in the offhand slot instead of being placed or replacing an hotbar slot.
An additional modifier key could be combined with the 2 other keys in order to place the offhand slot item into one of the backslot ones.

**Comment by Globox1997** [comment]
I think this will be added in the next update if I remember correctly

**Comment by Globox1997** [comment]
I just hope I added this in a later version.
