### ISSUE TITLE
Sword Behind Shield + Inverted Arsenal for Left Hand Mode

### ISSUE THREAD

**Issue by RetroGameDays36** [Globox1997/BackSlotAddon#5]
![For reference](https://user-images.githubusercontent.com/88062541/147006666-95eb7b05-2742-432e-a1bc-12a51690f19c.PNG)

Would be a neat little detail to add👍

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/BackSlotAddon/commit/b6825712906869ca9e88db83dcc67672904cca86](https://github.com/Globox1997/BackSlotAddon/commit/b6825712906869ca9e88db83dcc67672904cca86)
