### ISSUE TITLE
mod compatibility

### ISSUE THREAD

**Issue by Heamaci** [Globox1997/BackSlotAddon#6]
could there be compatibility with hardcore torches? It adds unlit and lit lanterns, but they can't be put in your belt slot.
So, you get dynamic lighting when it is lit and when it runs out of fuel, it will no longer emit light but still be equipped. 

https://www.curseforge.com/minecraft/mc-mods/hardcore-torches

**Comment by Globox1997** [comment]
[hardcore_torch_backslot_compat.zip](https://github.com/Globox1997/BackSlotAddon/files/8823033/hardcore_torch_backslot_compat.zip)
It is already compatible, made an example datapack which adds the lantern items to the backslotaddon lantern tag
